hacktech/modules/judging/__init__.py
import flask
blueprint = flask.Blueprint('judging', __name__, template_folder='templates')

import hacktech.modules.judging.routes

hacktech/modules/judging/routes.py
import flask

from hacktech.modules.judging import blueprint, helpers
from hacktech import auth_utils
from hacktech.modules.applications import helpers as app_helpers
import os
import json


@blueprint.route("/judge")
def judge():
    curpage = int(flask.request.args.get('page', 0))
    page_size = flask.session.get('page_size', 100)
    if page_size == "":
        page_size = 100
    else:
        page_size = int(page_size)
    flask.session['page_size'] = page_size
    if not auth_utils.check_login() or not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))
    info = helpers.get_all_application_links()
    total_pages = int(len(info) / page_size) + 1
    info = info[curpage * page_size:(curpage + 1) * page_size]
    return flask.render_template(
        "judge.html",
        info=info,
        headers=['Name', 'Status', "", 'Link'],
        page=curpage,
        total_pages=total_pages,
        page_size=page_size)


@blueprint.route("/judge_waivers")
def judge_waivers():
    curpage = int(flask.request.args.get('page', 0))
    page_size = flask.session.get('page_size', 100)
    if page_size == "":
        page_size = 100
    else:
        page_size = int(page_size)
    flask.session['page_size'] = page_size
    if not auth_utils.check_login() or not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))
    info = helpers.get_all_waiver_links()
    total_pages = int(len(info) / page_size) + 1
    info = info[curpage * page_size:(curpage + 1) * page_size]
    return flask.render_template(
        "judge.html",
        info=info,
        headers=['Name', 'Waiver Status', 'Medical Status', 'Waiver Link'],
        page=curpage,
        total_pages=total_pages,
        page_size=page_size)


@blueprint.route("/update_page_size", methods=['POST'])
def update_page_size():
    flask.session['page_size'] = flask.request.form.get('page_size', 100)
    if flask.session['page_size'] == "":
        flask.session['page_size'] = 100
    flask.session['page_size'] = int(flask.session['page_size'])
    return flask.redirect(flask.url_for("judging.judge"))


@blueprint.route("/view_application/<int:user_id>")
def view_application(user_id):
    if not auth_utils.check_login() or not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))
    info = helpers.get_application(user_id)
    status = helpers.get_status(user_id)
    return flask.render_template(
        "view_application.html", info=info, status=status)


@blueprint.route("/view_caltech_waiver/<int:user_id>")
def view_caltech_waiver(user_id):
    if not auth_utils.check_login() or not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))
    info = helpers.get_waiver(user_id, "caltech_waiver")
    info.update(helpers.get_waiver(user_id, "medical_info"))
    info['user_id'] = user_id
    status = helpers.get_waiver_status(user_id, "caltech_waiver")
    status.update(helpers.get_waiver_status(user_id, "medical_info"))
    return flask.render_template(
        "view_caltech_waiver.html", info=info, status=status)


@blueprint.route("/stats")
def show_stats():
    if not auth_utils.check_login() or not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))
    default_stats = helpers.get_current_stats()
    return flask.render_template(
        "stats.html", raw_data=json.dumps(default_stats))


@blueprint.route('/waivers/<waiver_type>/<filename>', methods=['GET'])
def uploaded_waiver_file(filename, waiver_type):
    ''' 
    This function should be collapsed with the function below
    '''
    if not auth_utils.check_login():
        return flask.redirect(flask.url_for("home"))

    cur_user_waiver = helpers.get_waiver(
        auth_utils.get_user_id(flask.session['username']), waiver_type)

    if cur_user_waiver != filename and not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))

    folder_path = "WAIVERS" if waiver_type == "caltech_waiver" else "MEDICAL"
    uploads = os.path.join(flask.current_app.root_path,
                           flask.current_app.config[folder_path])
    return flask.send_from_directory(uploads, filename, as_attachment=False)


@blueprint.route('/resume/<filename>', methods=['GET'])
def uploaded_file(filename):
    '''
    Serves the actual uploaded file.
    '''
    if not auth_utils.check_login():
        return flask.redirect(flask.url_for("home"))

    user_res_name = app_helpers.check_resume_exists(
        app_helpers.get_user_id(flask.session['username']))

    if user_res_name != filename and not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))
    uploads = os.path.join(flask.current_app.root_path,
                           flask.current_app.config['RESUMES'])
    return flask.send_from_directory(uploads, filename, as_attachment=False)


@blueprint.route('/judge/resumes', methods=['POST'])
def serve_resume_book():
    if not auth_utils.check_login() or not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))
    fields = flask.request.form.getlist("groups", None)
    if fields == None:
        return flask.redirect(flask.url_for("judging.judge"))

    helpers.generate_resume_book(fields)
    return flask.redirect(
        flask.url_for(
            "judging.uploaded_file", filename="hacktech_resume_book.pdf"))


@blueprint.route(
    '/judge_waivers/update/<waiver_type>/<int:user_id>', methods=['POST'])
def update_waiver_status(waiver_type, user_id):
    if not auth_utils.check_login() or not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))
    helpers.update_waiver_status(
        user_id,
        flask.request.form.get('new_status'),
        auth_utils.get_user_id(flask.session['username']), waiver_type)
    flask.flash('Status has been updated')
    return flask.redirect(
        flask.url_for('.view_caltech_waiver', user_id=user_id))


@blueprint.route('/judge/update/<int:user_id>', methods=['POST'])
def update_status(user_id):
    if not auth_utils.check_login() or not auth_utils.check_admin(
            flask.session['username']):
        return flask.redirect(flask.url_for("home"))
    helpers.update_status(user_id,
                          flask.request.form.get('new_status'),
                          flask.request.form.get('reimbursement_amount'),
                          app_helpers.get_user_id(flask.session['username']))
    flask.flash('Status has been updated')
    return flask.redirect(flask.url_for('judging.judge'))

hacktech/modules/judging/templates/judge.html
{% extends "layout.html" %}

{% block styles %}
  {{super()}}
{% endblock %}
{% block page %} 
<div class="jumbotron">
<div class='container'>
<div class="row">
  <div class="col-12 col-md-3" style="padding-left: 50px;">
    <div id="judgeViewOpt">
      <h4>Options</h4>
      Status types:
      </br>
      <input type="checkbox" name="display_tag" value="Accepted"/>
      <label class="checkbox-inline">Accepted</label>
      </br>
      <input type="checkbox" name="display_tag" value="In-Progress"/>
      <label class="checkbox-inline">In-progress</label>
      </br>
      <input type="checkbox" name="display_tag" value="Submitted"/>
      <label class="checkbox-inline">Submitted</label>
      </br>
      <input type="checkbox" name="display_tag" value="RSVPed"/>
      <label class="checkbox-inline">RSVPed</label>
      </br>
      <input type="checkbox" name="display_tag" value="Declined"/>
      <label class="checkbox-inline">Declined</label>
      </br>
      <input type="checkbox" name="display_tag" value="Rejected"/>
      <label class="checkbox-inline">Rejected</label>
      </br>
      <input type="checkbox" name="display_tag" value="Not Started"/>
      <label class="checkbox-inline">Not Started</label>
       <form class="form-inline" action="{{ url_for('judging.update_page_size', page=page) }}" method="post">
         <div id="pageSize" class="form-group">
            <label for="page_size">Entries per page: </label>
	    <input type="number" class="form-control" id="page_size" name="page_size" placeholder="{{page_size}}" />
	    <button type="submit" class="btn btn-primary">Go</button>
          </div>
          </form>
    </div>
  </div>
  <div class="col-12 col-md-9">
  <h4>Applicants</h4>    
  <table style="width:100%" id="judgingTable">
  <tr>
    {%for i in range(headers|length)%}
    <th>{{headers[i]}}</th>
    {%endfor%}
  </tr>
  {% for i in info %}
  <tr class='{{i.status}}'>
	  <td>{{page*page_size+loop.index}}. {{i.first_name}} {{i.last_name}} </td>
	  <td> {{i.status}}{{i.caltech_waiver_status}} </td>
	  <td> {{i.medical_info_status}}</td>
	  <td><a href="{{i.link}}">Go</a></td>
  </tr>
  {% endfor %}
</table>
  {%if page > 0%}
  <a href="{{ url_for(request.endpoint, page=page-1) }}"> Prev Page </a>
  {%endif%}

  <div id="pageJumpDiv">
    <div>
	{%if page >= 3 %}
	<a href="{{ url_for(request.endpoint, page=0) }}">1...</a>
	{%endif%}
	{%for i in range(2, 0, -1)%}
	  {%if page - i >= 0%}
	    <a href="{{ url_for(request.endpoint, page=page-i) }}"> {{page-i+1}} </a>  	
	  {%endif%}
  	{%endfor%}	
	 <a id="pageJumpCurPage" href="{{ url_for(request.endpoint, page=page) }}"> {{page+1}} </a>
	{%for i in range(1, 3)%}
          {%if page + i < total_pages%}
            <a href="{{ url_for(request.endpoint, page=page+i) }}"> {{page+i+1}} </a>
          {%endif%}
        {%endfor%}
	{%if page < total_pages - 3 %}
	<a href="{{ url_for(request.endpoint, page=total_pages - 1)}}">...{{total_pages}}</a>
        {%endif%}
    </div>
  </div>
  {%if total_pages > page + 1%}
  <a href="{{ url_for(request.endpoint, page=page+1) }}" id="nextPage"> Next Page </a>
  {%endif%}
  </div>
</div>
</div>
</div>
{% block scripts %}
  {{ super() }}
  <script>
    $('#judgeViewOpt :checkbox').prop('checked', true);
    // Bind visible checkboxes.
    $('#judgeViewOpt :checkbox').change(function() {
      toggle($(this).val(), this.checked);
    });  
    function toggle(tag, visibility){
      $("tr").each( function (){
        if ($(this).hasClass(tag))
        {
            $(this).toggle(visibility);
        }
      });
    }
  </script>
{% endblock %}
{% endblock %}

hacktech/modules/judging/templates/stats.html
{% extends "layout.html" %}

{% block styles %}
  {{super()}}
{% endblock %}
{% block scripts %}
  {{ super() }}
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.bundle.min.js"></script>
  <script src='{{ url_for("static", filename="js/search.js") }}'></script>
  <script>
    var data = {{raw_data | safe}};
    function new_chart(ctx, title, cur_data, cur_labels){
      new Chart(ctx, {
      type: 'bar',
      data: {
        labels: cur_labels,
        datasets: [{
            data: cur_data,
	    backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
	      
        }]
      },
      options: {
          title: {
              display: true,
              text: title
          },
	  scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        },
       legend: {
          display: false,
          labels: {
               // This more specific font property overrides the global property
               fontSize: 10
          }
        }      
      }
      });
    }
    var ctx = document.getElementById('c1').getContext('2d');
    new_chart(ctx, "Shirt Size", data.shirt_size.data, data.shirt_size.labels);
    var ctx = document.getElementById('c3').getContext('2d');
    new_chart(ctx, "Graduation Year", data.graduation_year.data, data.graduation_year.labels);
    var ctx = document.getElementById('c4').getContext('2d');
    new_chart(ctx, "Major", data.major.data, data.major.labels);
    var ctx = document.getElementById('c5').getContext('2d');
    new_chart(ctx, "Degree Type", data.degree_type.data, data.degree_type.labels);
    var ctx = document.getElementById('c6').getContext('2d');
    new_chart(ctx, "In state", data.in_state.data, data.in_state.labels);
    var ctx = document.getElementById('c7').getContext('2d');
    new_chart(ctx, "School", data.school.data, data.school.labels);
    var ctx = document.getElementById('c0').getContext('2d');
    new_chart(ctx, "Status", data.status.data, data.status.labels);
    var ctx = document.getElementById('c8').getContext('2d');
    new_chart(ctx, "Race", data.race.data, data.race.labels);
    var ctx = document.getElementById('c2').getContext('2d');
    new_chart(ctx, "Diet", data.diet.data, data.diet.labels);
    var ctx = document.getElementById('c10').getContext('2d');
    new_chart(ctx, "Gender", data.gender.data, data.gender.labels);
    document.getElementById("users_info").textContent += String(data.total_users);
    document.getElementById("application_info").textContent += String(data.total_applications);
    document.getElementById("waiver_info").textContent += String(data.waiver_status);

  </script>
{% endblock %}
{% block page %}
  <div class="container">
  <h2 class="text-center">Statistics</h2>


  <p id="users_info"> Total users on website: </p>

  <p id="application_info"> Total applications this year: </p>

  <p id="waiver_info"> Total people who submitted both : </p>

  {% for i in ['0', '1', '2'] %}
  <div id="observe">
	  <canvas id={{"c" + i}} width="100" height="100"></canvas>
  </div>
  {%endfor%}
  </hr>
  
  <h4 class="text-center">Demographics</h4>
  {% for i in ['3', '4', '5', '6', '7', '8', '9', '10'] %}
  <div id="observe">
          <canvas id={{"c" + i}} width="100" height="100"></canvas>
  </div>
  {% endfor %}
  </div>
  {% endblock %}

hacktech/modules/judging/templates/view_application.html
{% extends "layout.html" %}

{% block styles %}
  {{super()}}
{% endblock %}
{% block page %} 
  <div class = "jumbotron col-md-8 col-md-offset-2">
    <h2 class="text-center">Judging</h2>
    {% if info != None %}

      <label>Name: </label>
      {{info.first_name}} {{info.middle_name}} {{info.last_name}}
     
      <br>
      <label>18?: </label>
      {{info.is_18}}

      <br>
      <label>Phone Number: </label>
      {{info.phone}}

      <hr/>
      <label>School: </label>
      {{info.school}}

      <br/>
      <label>Major: </label>
      {{info.major}}

      <br/>
      <label>Degree Type: </label>
      {{info.degree_type}}

      <br/>
      <label>Graduation Year: </label>
      {{info.graduation_year}}

      <hr/>
      <label>GitHub Link: </label>
      <a href={{ "https://github.com/" ~ info.github}}>{{"https://github.com/"~info.github}}</a>

      <br/>
      <label>Linkedin Link: </label>
      <a href={{ "https://linkedin.com/in/" ~ info.linkedin}}>{{"https://linkedin.com/in/"~info.linkedin}}</a>

      <hr/>
      <label>Latino: </label>
      {{info.latino}}

      <br/>
      <label>Gender: </label>
      {{info.gender}}

      <br/>
      <label>Shirt Size: </label>
      {{info.shirt_size}}
            
      <hr/>
      <label>Transportation: </label>
      {{info.transportation}}
      
      <br/>
      <label>In state: </label>
      {{info.in_state}}
      
      <br/>
      <label>Bus From: </label>
      {{info.bus_from}}

      
      <br/>
      <label>Airport: </label>
      {{info.airport}}
      
      <hr/>
      <label>Why would you like to come to Hacktech 2022? </label>
      <br/>
      {{info.q1}}

      <hr/>
      <label>How did you stay connected with your friends/family over quarantine? Without technological limitations, how would you stay connected virtually? </label>
      <br/>
      {{info.q2}}

      <hr/>
      <label>Share one interesting thing - a math problem, history fact, mechanism to manufacture something, anything. </label>
      <br/>
      {{info.q3}}

      <hr/>
      <label>We want to improve Hacktech -- what would you like to see at Hacktech this year? Is there anything else you want us to know about you? </label>
      <br/>
      {{info.q4}}

      <hr/>
      <label>What virtual events would you like to see at Hacktech? (video game tournaments, Kahoot, minecraft server) </label>
      <br/>
      {{info.q5}}

      <hr/>
      <label>(<a href="https://nypost.com/2021/12/24/japanese-professor-invents-lickable-taste-the-tv-screen/" rel="noopener noreferrer">NY Post Article</a>) If your laptop screen could suddenly taste like any food in the world, what would it be? </label>
      <br/>
      {{info.q6}}
      <hr/>

      {% if info.resume is not none %}

      <div style="position: relative; text-align: center; height: 0; padding-bottom: 100%; overflow: hidden">
	      <iframe
			src={{info.resume_url}}
			frameBorder="0"
			seamless="seamless"
			style="margin: auto; position: absolute; top: 0; left: 0; width: 70%; height: 100%"
		></iframe>
      </div>
      {%else %}
	<p> No resume submitted! </p>
      {%endif%}
      <form action="{{ url_for('judging.update_status', user_id=info.user_id) }}" method="post">
      <div class="form-group">      
        <label> Reimbursement Amount </label>
	<div class="input-group">
   	  <span class="input-group-addon">$</span>
	    <input type="numbers" class="form-control" id="reimbursement_amount" value={{status.reimbursement_amt}} name="reimbursement_amount" disabled >
	</div>
      </div>
      <select class="form-control" name='new_status'>
        <option>Choose...</option>
	<option value="Accepted" {%if status.status == "RSVPed" or status.status == "Accepted" or status.status == "Declined"%} selected {%endif%}>Accept</option>
	<option value="Rejected" {%if status.status == "Rejected" %} selected {%endif%}>Reject</option>
      </select>
      <button type="submit" class="btn btn-default">Go</button>
      </form>
    {% else %}
      <p> User has not submitted their applications. </p>

    {% endif %}
 </div>
{% endblock %}

hacktech/modules/judging/templates/view_caltech_waiver.html
{% extends "layout.html" %}

{% block styles %}
  {{super()}}
{% endblock %}
{% block page %} 
  <div class = "jumbotron col-md-8 col-md-offset-2">
    <h2 class="text-center">Waivers</h2>
    {%if info.caltech_waiver_url == ""%}
    	No caltech waiver submitted!
    {%else%}
      <div style="position: relative; text-align: center; height: 0; padding-bottom: 100%; overflow: hidden">
	      <iframe
			src={{info.caltech_waiver_url}}
			frameBorder="0"
			seamless="seamless"
			style="margin: auto; position: absolute; top: 0; left: 0; width: 70%; height: 100%"
		></iframe>
      </div>
      {%endif%}
      <form action="{{ url_for('judging.update_waiver_status', user_id=info.user_id, waiver_type='caltech_waiver') }}" method="post">
      <select class="form-control" name='new_status'>
        <option>Choose...</option>
	<option value="Confirmed" {%if status.caltech_waiver_status == "Confirmed"%} selected {%endif%} >Confirm</option>
	<option value="Rejected" {%if status.caltech_waiver_status == "Rejected" %} selected {%endif%}>Reject</option>
      </select>
      <button type="submit" class="btn btn-default">Go</button>
      </form>


          {%if info.medical_info_url == ""%}
        No caltech waiver submitted!
    {%else%}
      <div style="position: relative; text-align: center; height: 0; padding-bottom: 100%; overflow: hidden">
              <iframe
                        src={{info.medical_info_url}}
                        frameBorder="0"
                        seamless="seamless"
                        style="margin: auto; position: absolute; top: 0; left: 0; width: 70%; height: 100%"
                ></iframe>
      </div>
      {%endif%}
      <form action="{{ url_for('judging.update_waiver_status', user_id=info.user_id, waiver_type='medical_info') }}" method="post">
      <select class="form-control" name='new_status'>
        <option>Choose...</option>
        <option value="Confirmed" {%if status.medical_info_status == "Confirmed"%} selected {%endif%} >Confirm</option>
        <option value="Rejected" {%if status.medical_info_status == "Rejected" %} selected {%endif%}>Reject</option>
      </select>
      <button type="submit" class="btn btn-default">Go</button>
      </form>
  </div>
{%endblock%}