hacktech/modules/waivers/__init__.py
import flask
blueprint = flask.Blueprint('waivers', __name__, template_folder='templates')

import hacktech.modules.waivers.routes

hacktech/modules/waivers/routes.py
import flask
import os
from hacktech import auth_utils
from hacktech.modules.waivers import blueprint, helpers
import json
from hacktech.modules.judging import helpers as judging_helpers


@blueprint.route("/waivers")
def waivers():
    if not auth_utils.check_login():
        return auth_utils.login_redirect()
    email = flask.session['username']
    user_id = auth_utils.get_user_id(email)
    return flask.render_template(
        "waivers.html",
        RSVPed=(judging_helpers.get_status(user_id)['status'] == "RSVPed"),
        caltech_waiver=helpers.get_waiver_status(user_id, "caltech_waiver"),
        medical_info=helpers.get_waiver_status(user_id, "medical_info"))


@blueprint.route("/waivers/caltech_waiver")
def caltech_waiver():
    return general_waiver(
        "caltech_waiver",
        link=
        "https://drive.google.com/file/d/1GjhzwhWJ9EBUyjagxajQFY0dHs_SKAn_/view?usp=sharing",
        title=
        "CONSENT, RELEASE AND ASSUMPTION OF RISK FOR PARTICIPATION IN HACKTECH AT CALTECH MARCH 6-8, 2020"
    )


@blueprint.route("/waivers/medical_information")
def medical_information():
    return general_waiver(
        "medical_info",
        link=
        "https://drive.google.com/file/d/1sWA9L2nLlLCI36IFR6D-eN2v-oWQtebA/view?usp=sharing",
        title="MEDICAL INFORMATION DISCLOSURE FOR HACKTECH 2020")


def general_waiver(waiver_type, link, title):
    if not auth_utils.check_login():
        return auth_utils.login_redirect()
    email = flask.session['username']
    # TODO: implement
    #status = helpers.submitted_caltech_waiver(email, waiver_type)
    form_info = judging_helpers.get_waiver(
        auth_utils.get_user_id(email), waiver_type)
    form_info['waiver_name'] = form_info[waiver_type + '_url'].split("/")[-1]
    form_info['waiver_url'] = form_info[waiver_type + '_url']
    form_info['waiver_update'] = flask.url_for(
        ".update_{0}".format(waiver_type))
    form_info['waiver_type'] = waiver_type
    return flask.render_template(
        "caltech_waiver.html",
        form_info=form_info,
        waiver_type=waiver_type,
        link=link,
        title=title)


@blueprint.route("/waivers/update_caltech_waivers", methods=["POST"])
def update_caltech_waiver():
    if not auth_utils.check_login():
        return auth_utils.login_redirect()
    email = flask.session['username']
    if 'caltech_waiver' in flask.request.files:
        waiver_file = flask.request.files['caltech_waiver']
    else:
        flask.flash("Please upload your filled waiver!")
        flask.redirect(flask.url_for(".caltech_waiver"))

    helpers.save_info(email, waiver_file, "WAIVERS", "caltech_waiver")
    flask.flash(
        "Thanks for submitting a waiver! A Hacktech organizer will check and make sure that your waiver is complete."
    )
    return flask.redirect(flask.url_for(".waivers"))


@blueprint.route("/waivers/update_medical_info", methods=["POST"])
def update_medical_info():
    if not auth_utils.check_login():
        return auth_utils.login_redirect()
    email = flask.session['username']
    if 'medical_info' in flask.request.files:
        waiver_file = flask.request.files['medical_info']
    else:
        flask.flash("Please upload your filled medical information!")
        flask.redirect(flask.url_for(".medical_information"))

    helpers.save_info(email, waiver_file, "MEDICAL", "medical_info")
    flask.flash(
        "Thanks for submitting your medical information! A Hacktech organizer will check and make sure that your info is complete."
    )
    return flask.redirect(flask.url_for(".waivers"))

hacktech/modules/waivers/templates/caltech_waiver.html
{% extends "layout.html" %}

{% block styles %}
  {{super()}}
{% endblock %}
{% block page %}
<div class = "jumbotron col-md-6 col-md-offset-3">
	    <h3 class="text-center">{{title}}</h3> 
    <p> Please <a href={{link}}> go here </a> to download the fillable PDF, and upload it below.</p>
    <form action={{form_info.waiver_update}} method="post"} enctype="multipart/form-data">
      <div class="form-group">
        <label class="control-label" for="resume">Please upload the completed waiver/form.</label>
	{%if form_info.waiver_url != None and  form_info.waiver_url != "" %}
	<span class="input-group-addon" id="uploadFileText">Current document on file: <a href={{form_info.waiver_url}}> <u>{{form_info.waiver_name}}</u> </a></span>
	{% else %}
	<span class="input-group-addon" id="uploadFileText">Upload</span>
	{% endif %}
	<input type="file" class="form-control" name={{form_info.waiver_type}} aria-describedby="uploadFileText" required>
      </div>
      <button type="submit" class="btn btn-success" value="Submit" name="Submit">Submit</button>
    </form>
</div>
{% endblock %}

hacktech/modules/waivers/templates/medical_info.html
{% extends "layout.html" %}

{% block styles %}
  {{super()}}
{% endblock %}
{% block page %}
<div class = "jumbotron">
    <div id="application_form" class="col-md-8 col-md-offset-2">
      <h3 class="text-center">Hacktech 2022 Medical Form</h3>
        <form action="{{url_for('waivers.update_medical_information')}}" method="post"} enctype="multipart/form-data">
          <div class="row">
              <div class="form-group col-md-12">
                <label class="control-label"  for="diet">Dietary Needs (i.e. vegetarian)</label> 
                <textarea  class="form-control" id="diet" name="diet" rows="2"></textarea>
              </div>
              <div class="form-group col-md-12">
                <label class="control-label"  for="allergy">Please list any allergies (food, medication, or other) and describe reactions.</label>
                <textarea  class="form-control" id="allergy" name="allergy" rows="2"></textarea>
             </div>
             <div class="form-group col-md-12">
                <label class="control-label"  for="medicalCondition">Please list any medical conditions or restrictions that Hacktech organizers should be aware of.</label>
                <textarea  class="form-control" id="medicalCondition" name="medicalCondition" rows="3"></textarea>
             </div>
             <div class="form-group col-md-12">
                <label class="control-label"  for="medicine">Please list medications you are using.</label>
                <textarea  class="form-control" id="medicine" name="medicine" rows="3"></textarea>
             </div>
          </div>
	  <p> If you need accessibility accommodations or have any other inquiries, please email us at team@hacktech.app! </p>
          <p><u><b>Emergency Contact Information</b></u> (A parent/guardian or someone who can make medical decisions on your behalf) </p>
          <div class="row">
            <div class="form-group col-md-6">
              <label class="control-label"  for="emergencyName">Name</label>
              <input type="text" class="form-control" name="emergencyName"></input>
            </div>
            <div class="form-group col-md-6">
              <label class="control-label"  for="emergencyRelation">Relationship To You</label>
              <input type="text" class="form-control" name="emergencyRelation" required></input>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-6">
              <label class="control-label"  for="emergencyPhone">Phone</label>
              <input type="text" class="form-control" name="emergencyPhone"></input>
            </div>
            <div class="form-group col-md-6">
              <label class="control-label"  for="emergencyAltPhone">Alternate Phone</label>
              <input type="text" class="form-control" name="emergencyAltPhone"></input>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-6">
              <label class="control-label"  for="physicianName">Family Physician</label>
              <input type="text" class="form-control" name="physicianName"></input>
            </div>
            <div class="form-group col-md-6">
              <label class="control-label"  for="physicianPhone">Physician Office Phone</label>
              <input type="text" class="form-control" name="physicianPhone"></input>
            </div>
          </div>
          <p><u><b>Insurance Information</b></u></p>
          <div class="row">
            <div class="form-group col-md-6">
              <label class="control-label"  for="insuranceCompany">Company</label>
              <input type="text" class="form-control" name="emergencyPhone"></input>
            </div>
            <div class="form-group col-md-6">
              <label class="control-label"  for="insurancePhone">Phone</label>
              <input type="text" class="form-control" name="insurancePhone"></input>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-6">
              <label class="control-label"  for="insurancePolicy">Policy # / Info</label>
              <input type="text" class="form-control" name="insurancePolicy"></input>
            </div>
            <div class="form-group col-md-6">
              <label class="control-label"  for="insurancePreAuth">Is Pre-Authorization Required</label>
              <div class="radio-inline">
	            <label class="radio-inline">
                <input type="radio" name="insurancePreAuth" value="True"> Yes </label>
	            <label class="radio-inline">
                <input type="radio" name="insurancePreAuth" value="False"> No </label>
                <label class="radio-inline">
                <input type="radio" name="insurancePreAuth" value="N/A"> N/A </label>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-12">
              <label class="control-label"  for="insuranceDetail">Other Detail</label>
              <textarea  class="form-control" name="insuranceDetail" rows="3"></textarea>
            </div>
          </div>
         <button type="submit" class="btn btn-success" value="Submit" name="Submit" {%if submitted or app_end %} disabled {%endif%}>Submit!</button>
        </form>
    </div>
</div>
{% endblock %}

hacktech/modules/waivers/templates/waivers.html
{% extends "layout.html" %}

{% block styles %}
  {{super()}}
{% endblock %}
{% block page %}
<div class = "jumbotron col-md-8 col-md-offset-2" style="text-align:center;">
{% if RSVPed %}

<h2 class="text-center">Hacktech Waivers</h2>
<div class = "col-md-12">
<p> Please submit the following waivers! We need them before you get on a bus or arrive to campus, 
whichever one is earlier. You WILL not be able to board the bus without a copy of the waivers, either
printed out or submitted through the portal here. </p>
<hr>
</div>
<div class ="row">
  <div class = "col-md-6">
    <p>Status: {{caltech_waiver}}</p>
    <a href="{{url_for('waivers.caltech_waiver')}}" class="btn btn-default">Caltech Waiver</a>
    <p><small>Waiver required by Caltech for consent, release, and assumption of risk for participation in Hacktech. </small></p>
  </div>
  <div class = "col-md-6">
  <p>Status: {{medical_info}}</p>
  <a href="{{url_for('waivers.medical_information')}}" class="btn btn-default">Medical Information</a>
  <p><small>Medical form required by Caltech for emergency contact information and any medical needs. </small></p>
  </div>
</div>
{% else %}

Woops! We're not sure how you wondered onto this page....

{% endif %}
</div>
{% endblock %}