hacktech/modules/account/__init__.py
import flask
blueprint = flask.Blueprint('account', __name__, template_folder='templates')

import hacktech.modules.account.routes

hacktech/modules/account/routes.py
import flask

from hacktech import auth_utils
from hacktech.modules.account import blueprint, helpers
import json


@blueprint.route("/create")
def create_account():
    """Provides a form to confirm an account."""
    partial = flask.request.args.get(
        "partial",
        '{"email":"", "first_name":"", "middle_name":"", "preferred_name":"", "last_name":"", "dob":""}'
    )
    partial = json.loads(partial)
    return flask.render_template("request_account.html", partial=partial)


@blueprint.route("/create/submit", methods=["POST"])
def create_account_submit():
    """Handles an account creation request."""
    email = flask.request.form.get("email", None)
    password = flask.request.form.get("password", None)
    password2 = flask.request.form.get("password2", None)
    first_name = flask.request.form.get("first_name", None)
    middle_name = flask.request.form.get("middle_name", None)
    preferred_name = flask.request.form.get("preferred_name", None)
    last_name = flask.request.form.get("last_name", None)
    dob = flask.request.form.get("date_of_birth", None)
    partial = {}
    partial["email"] = email
    partial["first_name"] = first_name
    partial["middle_name"] = middle_name
    partial["preferred_name"] = preferred_name
    partial["last_name"] = last_name
    partial["dob"] = dob
    if email is None or password is None or password2 is None or first_name is None or last_name is None or dob is None or dob == "" or dob == "0000-00-00":
        flask.flash("Make sure you fill out all parts of the form!")
        return flask.redirect(flask.url_for("account.create_account"))
    if not helpers.check_valid_dob(dob):
        flask.flash("Make sure that your birthday is formatted as 2022-03-04")
        return flask.redirect(
            flask.url_for(
                "account.create_account", partial=json.dumps(partial)))
    if '@' not in email and '.' in email:
        flask.flash("Make sure you enter your email correctly!")
        return flask.redirect(
            flask.url_for(
                "account.create_account", partial=json.dumps(partial)))
    success, error_msg = helpers.handle_create_account(
        email, password, password2, first_name, middle_name, preferred_name,
        last_name, dob)
    if success:
        flask.flash("You've successfully created an account!")
        flask.session['username'] = email
    else:
        if error_msg != "":
            flask.flash(error_msg)
        return flask.redirect(
            flask.url_for(
                "account.create_account", partial=json.dumps(partial)))
    return flask.redirect(flask.url_for("home"))

hacktech/modules/account/templates/create_account.html
{% extends "layout.html" %}

{% block page %}
<h2>Create An Account</h2>
<p style="color: red">All fields are required.</p>

<form action="{{ url_for('account.create_account_submit', create_account_key=key) }}" method="post">
  <p>Choose a username and password.</p>
  <table class="form">
    <tr>
      <td>Username</td>
      <td><input type="text" name="username" /></td>
    </tr>
    <tr>
      <td>Password</td>
      <td><input type="password" name="password" /></td>
    </tr>
    <tr>
      <td>Confirm password</td>
      <td><input type="password" name="password2" /></td>
    </tr>
  </table>
  <p>Please fill in/verify your personal information.</p>
  <table class="form">
    <tr>
      <td>First Name</td>
      <td>{{ user_data['first_name'] }}</td>
    </tr>
    <tr>
      <td>Last Name</td>
      <td>{{ user_data['last_name'] }}</td>
    </tr>
    <tr>
      <td>Matriculation Year</td>
      <td>{{ user_data['entry_year'] }}</td>
    </tr>
    <tr>
      <td>Graduation Year</td>
      <td>{{ user_data['graduation_year'] }}</td>
    </tr>
    <tr>
      <td>Email</td>
      <td>{{ user_data['email'] }}</td>
    </tr>
    <tr>
      <td>Birthday</td>
      <td><input type="text" name="birthday" placeholder="YYYY-MM-DD" /></td>
    </tr>
  </table>
  <button type="submit">Submit</button>
</form>
{% endblock page %}

hacktech/modules/account/templates/request_account.html
{% extends "layout.html" %}

{% block page %}
<div class="col-md-6 col-md-offset-3" style="float: none">
  <div class="jumbotron">
    <h2 class="text-center">Create an account</h2>
    <form action="{{ url_for('account.create_account_submit') }}" method="post">
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="email" class="required">Email</label>
            <input type="text" class="form-control" id="email" name="email" placeholder="Enter your email" value="{{partial.email}}" required autofocus/>
	  </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="password" class="required">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" required/>
	  </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="password2" class="required">Confirmed Password</label>
            <input type="password" class="form-control" id="password2" name="password2" placeholder="Enter your password" required/>
	  </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="first_name" class="required">First Name</label>
            <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter your first name" value="{{partial.first_name}}" required/>
	  </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="middle_name">Middle Name</label>
            <input type="text" class="form-control" id="middle_name" name="middle_name" placeholder="Enter your middle name" value="{{partial.middle_name}}"/>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="last_name" class="required">Last Name</label>
            <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter your last name" value="{{partial.last_name}}" required/>
	  </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="preferred_name">Preferred Name</label>
	    <input type="text" class="form-control" id="preferred_name" name="preferred_name" placeholder="Enter your preferred name" value="{{partial.preferred_name}}"/>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="date_of_birth" class="required">Date Of Birth</label>
            <input type="date" class="form-control" id="date_of_birth" name="date_of_birth" placeholder="YYYY-MM-DD" value="{{partial.dob}}"/>
	  </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock page %}